services:
  mysafetyreport:
    container_name: safetyreport
    image: ghcr.io/fentanest/safetyreport:latest
    ports:
      - 6819:6819
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Seoul
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_POLL_INTERVAL: 43200
    restart: unless-stopped
