services:
  mysafetyreport:
    container_name: safetyreport
    image: ghcr.io/fentanest/safetyreport:latest
    ports:
      - 6819:6819
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data:/app/data
    restart: unless-stopped
